name: Call Reusable Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: gargimehendale/github-actions-ci-maven/.github/workflows/main.yml@main
    with:
      docker_image_name: "java-maven-ci-project-app"
      mvn_options: "-B"
      mvn_actions: "package"
      mvn_file: "pom.xml"
      jdk_version: "21"  
      jdk_distribution: "temurin"
    secrets:
      HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
      HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
      PAT_FOR_GITHUB: ${{ secrets.PAT_FOR_GITHUB }}
