name: Call Reusable Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: gargimehendale/github-actions-ci-maven-template/.github/workflows/main.yml@main
    with:
      docker_image_name: "java-maven-ci-project-app"
      mvn_options: "-B"
      mvn_actions: "package"
      mvn_file: "pom.xml"
      jdk_version: "21"  
      jdk_distribution: "temurin"
    secrets:
      HCL_CLIENT_ID: ${{ secrets.HCL_CLIENT_ID }}
      HCL_CLIENT_SECRET: ${{ secrets.HCL_CLIENT_SECRET }}
      HCL_ORGANIZATION_ID: ${{ secrets.HCL_ORGANIZATION_ID }}
      HCL_PROJECT_ID: ${{ secrets.HCL_PROJECT_ID }}
      # DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      # JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      # JFROG_URL: ${{ secrets.JFROG_URL }}
      # JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      # JFROG_DOMAIN: ${{ secrets.JFROG_DOMAIN }}
      # JFROG_DOCKER_TOKEN: ${{ secrets.JFROG_DOCKER_TOKEN }}
      # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # TEST_SECRET: ${{ secrets.TEST_SECRET }}
